# Generated by Django 5.1.7 on 2025-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Обычный пользователь'), ('guest', 'Гость')], default='guest', max_length=30),
        ),
    ]
