# Generated by Django 5.1.7 on 2025-03-28 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата отчёта')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Проданных товаров')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Выручка')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
            },
        ),
    ]
